##### Patching Backend Deployment for Notification Service #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: notification-service # Patch labels
  template:
    metadata:
      labels:
        app: notification-service # Patch labels
    spec:
      containers:
        - name: app
          image: helabooking/notification-service:latest # Patch image
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://notificationdb-svc:5432/notificationdb" # Patch DB URL
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: pgsql-notification-db-password # Patch password key
          livenessProbe:
            httpGet:
              port: 8085 # Patch port
          readinessProbe:
            httpGet:
              port: 8085 # Patch port
