###### Patching environment variables for dev environment ######
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignored # This patch targets specific resources by label or name matching below
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev" # Patch the profile
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-env-dev.svc.cluster.local" # Patch RabbitMQ host
