##### Patching resource requests and limits for dev environment ######
############# Databases #############
# Applies to all databases
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-resources-patch
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: pico-node
      containers:
        - name: postgres
          resources:
            requests:
              memory: "100Mi"
              cpu: "75m"
            limits:
              memory: "256Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
        storageClassName: longhorn-sc
