##### Patching resource requests and limits for dev environment ######
############# Backend Services #############
# Applies to all backend services
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-resources-patch
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: galaxy-node
      containers:
        - name: app
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            initialDelaySeconds: 90
            periodSeconds: 10
