###### Patching Horizontal Pod Autoscaler for dev environment ######
# HPA Patch for Frontend Service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-frontend
spec:
  minReplicas: 0
  maxReplicas: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
