##### Patching resource requests and limits for dev environment ######
############# Backend Services #############
# Applies to all backend services
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-resources-patch
spec:
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            initialDelaySeconds: 300
            periodSeconds: 10
