##### Patching resource requests and limits for dev environment ######
############# Frontend #############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
############# Backend Services #############
# Applies to all backend services
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-resources-patch
spec:
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
target:
  kind: Deployment
  labelSelector: "app in (user-service, event-service, booking-service, ticketing-service, notification-service, audit-service)"
---
############# Databases #############
# Applies to all databases
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-resources-patch
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
target:
  kind: StatefulSet
  labelSelector: "app in (userdb-pgsql, eventdb-pgsql, bookingdb-pgsql, ticketingdb-pgsql, notificationdb-pgsql, auditdb-pgsql)"
